export enum RunOutcome {
  SUBMITTED = "SUBMITTED",
  VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED",
  FAILED = "FAILED",
  ESCALATED = "ESCALATED",
  CANCELLED = "CANCELLED",
  SKIPPED = "SKIPPED",
}
