export enum AtsType {
  WORKDAY = "WORKDAY",
  GREENHOUSE = "GREENHOUSE",
  LEVER = "LEVER",
  ASHBY = "ASHBY",
  ICIMS = "ICIMS",
  SMARTRECRUITERS = "SMARTRECRUITERS",
  TALEO = "TALEO",
  SAP = "SAP",
  CUSTOM = "CUSTOM",
}
